spring:
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springbatch            # 数据库名称
    username: root
    password: 123456
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
   batch:
     initialize-schema: always
#     job:
#       names: parentJobs
     job:
      enabled: false   # 加了这个job就不会在启动时自动执行了  演示jobLaunchaerDemo时使用
 
 
 

